# ./Taskfile.yaml
# Taskfile for Python Project Container Management and Utilities

version: '3'
dotenv: [".env"] # Loads variables from .env file

vars:
  # --- AI Task Variables ---
  AI_OUTPUT_FILE: ai_context.txt
  # Updated regex to include .html files
  INCLUDE_EXTENSIONS_REGEX: '\.(py|yaml|json|md|gitignore|txt|nix|Dockerfile|html)$|^(Taskfile\.yaml|requirements\.txt)$'
  MAX_FILE_SIZE_KB: 500
  # Excludes look correct.
  EXCLUDE_PATHS_REGEX: '(^\.git/|^\.venv/|^__pycache__/|^\.DS_Store|^\.vscode/|ai_context\.txt)'

  # --- Container Variables (reading from .env) ---
  REGISTRY_PATH: '{{.REGISTRY_PATH | default .Env.REGISTRY_PATH}}'
  IMAGE_NAME: '{{.IMAGE_NAME | default .Env.IMAGE_NAME}}'
  # Default IMAGE_TAG comes from .env, falling back to "latest"
  IMAGE_TAG: '{{.IMAGE_TAG | default .Env.IMAGE_TAG | default "latest"}}'

tasks:
  # --- Python Linting and Formatting ---
  format:py:
    summary: "Formats Python code using black."
    cmds:
      # Targets current directory '.' - Correct for app.py in root.
      - black .
    preconditions:
      # Checks for black command - Correct.
      - sh: "command -v black"
        msg: "'black' command not found. Is it installed via Nix?"
    silent: false

  lint:py:
    summary: "Lints Python code using flake8."
    cmds:
      # Targets current directory '.' - Correct for app.py in root.
      - flake8 .
    preconditions:
      # Checks for flake8 command - Correct.
      - sh: "command -v flake8"
        msg: "'flake8' command not found. Is it installed via Nix?"
    silent: false

  # --- AI Context Generation ---
  ai:
    summary: "Generates a context file for AI interaction."
    preconditions:
      # Checks look appropriate for the script's needs (root, git, tools).
      - sh: '[ "$(pwd)" = "{{.TASKFILE_DIR}}" ]'
        msg: "AI task must be run from the project root directory ({{.TASKFILE_DIR}})."
      - sh: "[ -d .git ]"
        msg: "AI task should be run from the root of a Git repository."
      - sh: "command -v git"
        msg: "'git' command not found."
      - sh: "command -v grep"
        msg: "'grep' command not found."
    desc: |
      # Description clearly explains the process and uses vars. Good.
      Generates a file ({{.AI_OUTPUT_FILE}}) containing structured context for an AI,
      tailored for this Python/GCP project using shell commands.
      NOTE: Inclusion/Exclusion rules are defined in Taskfile vars. Must be run from project root.
      Includes:
      1. User prompt (interactive).
      3. Key Tool Versions & Environment Details.
      4. Git status summary.
      5. Project directory structure (Level 2).
      6. Content of relevant files (formatted) based on regex: {{.INCLUDE_EXTENSIONS_REGEX}}
         Excluding paths based on regex: {{.EXCLUDE_PATHS_REGEX}}
         Respects .gitignore. Max file size: {{.MAX_FILE_SIZE_KB}}KB.
    cmds:
      - |
        set -e # Exit immediately if a command exits with a non-zero status.

        # --- Configuration ---
        OUTPUT_FILE="{{.AI_OUTPUT_FILE}}"
        MAX_SIZE_BYTES=$(( {{.MAX_FILE_SIZE_KB}} * 1024 ))
        INCLUDE_REGEX='{{.INCLUDE_EXTENSIONS_REGEX}}'
        EXCLUDE_REGEX='{{.EXCLUDE_PATHS_REGEX}}'

        # --- Initialization ---
        echo "Generating AI context in $OUTPUT_FILE..."
        > "$OUTPUT_FILE" # Overwrite/create the file

        # --- Section: User Prompt ---
        printf "### Prompt\n\n" >> "$OUTPUT_FILE"
        echo "---------------------------------------------------------------------" >&2
        echo "Enter a prompt for the AI (e.g., 'Refactor X module', 'Add Y feature to script', 'Review changes in compute.tf')." >&2
        echo "Be specific about goals, files, resources, or errors." >&2
        echo "---------------------------------------------------------------------" >&2
        USER_PROMPT=""
        while [ -z "$USER_PROMPT" ]; do
          read -r -p "> " USER_PROMPT
          if [ -z "$USER_PROMPT" ]; then
            echo "Prompt cannot be empty. Please try again." >&2
          fi
        done
        printf "%s\n\n" "$USER_PROMPT" >> "$OUTPUT_FILE"

        # --- Section: Environment Context ---
        printf "### Environment Context\n\n" >> "$OUTPUT_FILE"
        printf "OS Type: " >> "$OUTPUT_FILE"
        { uname -s || echo "Unknown"; } >> "$OUTPUT_FILE"
        printf "Key tool versions:\n" >> "$OUTPUT_FILE"
        { printf "  Python: "; python --version || python3 --version || echo "Not found"; } >> "$OUTPUT_FILE"
        { printf "  gcloud: "; gcloud version | grep "Google Cloud SDK" || echo "Not found"; } >> "$OUTPUT_FILE"
        printf "Other potentially relevant tools:\n" >> "$OUTPUT_FILE"
        { printf "  jq: "; command -v jq >/dev/null && echo "Available" || echo "Not found"; } >> "$OUTPUT_FILE"
        { printf "  flake8: "; command -v flake8 >/dev/null && echo "Available" || echo "Not found"; } >> "$OUTPUT_FILE"
        { printf "  black: "; command -v black >/dev/null && echo "Available" || echo "Not found"; } >> "$OUTPUT_FILE"
        printf "Relevant environment variables:\n" >> "$OUTPUT_FILE"
        printf "  GOOGLE_CLOUD_PROJECT: %s\n" "${GOOGLE_CLOUD_PROJECT:-<unset>}" >> "$OUTPUT_FILE"
        printf "  GOOGLE_REGION: %s\n" "${GOOGLE_REGION:-<unset>}" >> "$OUTPUT_FILE"
        if [ -f ".idx/dev.nix" ]; then printf "Nix environment definition found in included .idx/dev.nix file.\n"; fi >> "$OUTPUT_FILE"
        printf "\n\n" >> "$OUTPUT_FILE"

        # --- Section: Git Status ---
        printf "### Git Status (Summary)\n\n" >> "$OUTPUT_FILE"
        printf "Provides context on recent local changes (after potential formatting):\n\n" >> "$OUTPUT_FILE"
        { git status --short || echo "Failed to get git status (maybe not a git repo?)."; } >> "$OUTPUT_FILE"
        printf "\n\n" >> "$OUTPUT_FILE"

        # --- Section: Project Structure ---
        printf "### Project Structure (Top Levels)\n\n" >> "$OUTPUT_FILE"
        printf "Directory layout (up to 2 levels deep):\n\n" >> "$OUTPUT_FILE"
        { tree -L 2 -a -I '.git|.venv|__pycache__|.DS_Store|.idx|.vscode|ai_context.txt' || ls -Ap | grep '/$' || echo "'tree' command not found, using 'ls'."; } >> "$OUTPUT_FILE"
        printf "\n\n" >> "$OUTPUT_FILE"

        # --- Section: Relevant File Contents ---
        printf "### Relevant Code Files Follow\n\n" >> "$OUTPUT_FILE"

        # --- Helper Function ---
        append_file_content() {
          local FILE="$1"
          local OUTPUT_FILE_INNER="$2"
          local MAX_BYTES="$3"
          local FILE_SIZE_BYTES
          if [ ! -f "$FILE" ] || [ ! -r "$FILE" ] || [ -L "$FILE" ]; then return; fi
          FILE_SIZE_BYTES=$(stat -c %s "$FILE" 2>/dev/null || stat -f %z "$FILE" 2>/dev/null || echo 0)
          if [ "$FILE_SIZE_BYTES" -eq 0 ]; then echo "Skipping (empty file): $FILE" >&2; return; fi
          if [ "$FILE_SIZE_BYTES" -gt "$MAX_BYTES" ]; then echo "Skipping (too large: ${FILE_SIZE_BYTES}B > ${MAX_BYTES}B): $FILE" >&2; return; fi
          {
            printf "\n======== FILE: %s ========\n" "$FILE"
            cat "$FILE"
            printf "\n======== END FILE: %s ========\n\n" "$FILE"
          } >> "$OUTPUT_FILE_INNER" || { echo "Error processing file: $FILE" >&2; return 1; }
          echo "Included: $FILE (${FILE_SIZE_BYTES}B)" >&2
        }

        # --- File Processing (Using Process Substitution - Reverted to Reference Method) ---
        echo "Filtering and processing files tracked/untracked by Git..." >&2
        # Use Process Substitution < <(...) which worked in the reference Taskfile
        while IFS= read -r file_path; do
              # Skip the output file itself
              if [ "$file_path" = "./$OUTPUT_FILE" ]; then continue; fi

              # Call the helper function
              append_file_content "$file_path" "$OUTPUT_FILE" "$MAX_SIZE_BYTES"
        # Process substitution feeds the pipeline output to the loop
        done < <(git ls-files -co --exclude-standard | grep -E "$INCLUDE_REGEX" | grep -vE "$EXCLUDE_REGEX")

        # --- Explicit Additions (Fallback/Guarantee) ---
        echo "Checking for explicit additions..." >&2
        # This loop remains as a fallback
        for f in ./Taskfile.yaml ./requirements.txt ./requirements-dev.txt; do
            if [ "$f" = "./$OUTPUT_FILE" ]; then continue; fi
            # Only add if file exists and wasn't already added by the main loop
            if [ -f "$f" ] && ! grep -qP "======== FILE: \./?$f ========" "$OUTPUT_FILE"; then
                append_file_content "$f" "$OUTPUT_FILE" "$MAX_SIZE_BYTES"
            fi
        done

        echo "Successfully generated AI context in $OUTPUT_FILE"
    silent: false # Show command output for easier debugging

  # --- Container Management ---
  build:
    summary: Build the container image using Docker.
    desc: |
      # Desc reflects reverted tagging logic. Good.
      Builds the Docker image using the Dockerfile in the current directory.
      Uses REGISTRY_PATH, IMAGE_NAME, IMAGE_TAG from .env file (or defaults).
      Example: task build            # Builds with tag from .env or 'latest'
               task build TAG=v1.0.1 # Overrides tag to v1.0.1
    vars:
      # TAG defaults correctly to global IMAGE_TAG, allows override. Correct.
      TAG: '{{.TAG | default .IMAGE_TAG }}'
    preconditions:
      # Checks essential vars, docker command, Dockerfile existence. Correct.
      - sh: '[ -n "$REGISTRY_PATH" ]'
        msg: "Error: REGISTRY_PATH is not set in .env file or environment."
      - sh: '[ -n "$IMAGE_NAME" ]'
        msg: "Error: IMAGE_NAME is not set in .env file or environment."
      - sh: "command -v docker"
        msg: "'docker' command not found."
      - sh: "[ -f Dockerfile ]"
        msg: "Dockerfile not found in the current directory."
    cmds:
      # Constructs image name correctly using resolved TAG. Correct.
      - |
        set -e
        IMG="${REGISTRY_PATH}/${IMAGE_NAME}:{{.TAG}}"
        echo "Building image: $IMG ..."
        docker build -t "$IMG" .
        echo "Build complete: $IMG"
    silent: false

  tag:
    summary: Apply an additional tag to the locally built image.
    desc: |
      # Desc matches functionality. Good.
      Tags the image identified by REGISTRY_PATH/IMAGE_NAME:SOURCE_TAG with a NEW_TAG.
      Example: task tag NEW_TAG=v1.0.0                # Tags image with default tag (from .env or 'latest') as v1.0.0
               task tag SOURCE_TAG=v1.1 NEW_TAG=stable # Tags image v1.1 as stable
    vars:
      # Defaults source tag correctly. Correct.
      SOURCE_TAG: '{{.SOURCE_TAG | default .IMAGE_TAG }}'
      # No default for NEW_TAG - Correctly removed the empty default.
    preconditions:
      # Checks essential vars, NEW_TAG presence, docker command. Correct.
      - sh: '[ -n "$REGISTRY_PATH" ]'
        msg: "Error: REGISTRY_PATH is not set in .env file or environment."
      - sh: '[ -n "$IMAGE_NAME" ]'
        msg: "Error: IMAGE_NAME is not set in .env file or environment."
      - sh: '[ -n "{{.NEW_TAG}}" ]'
        msg: "Error: NEW_TAG variable must be provided. Usage 'task tag NEW_TAG=<new-tag> [SOURCE_TAG=<source>]'"
      - sh: "command -v docker"
        msg: "'docker' command not found."
    cmds:
      # Constructs image names and runs docker tag. Correct.
      - |
        set -e
        SOURCE_IMG="${REGISTRY_PATH}/${IMAGE_NAME}:{{.SOURCE_TAG}}"
        TARGET_IMG="${REGISTRY_PATH}/${IMAGE_NAME}:{{.NEW_TAG}}"
        echo "Tagging $SOURCE_IMG as $TARGET_IMG ..."
        docker tag "$SOURCE_IMG" "$TARGET_IMG"
        echo "Tagging complete."
    silent: false

  push:
    summary: Push the container image to the registry.
    desc: |
      # Desc reflects reverted tagging logic. Good.
      Pushes the specified tag to the registry.
      Default Tag: From .env variable IMAGE_TAG or 'latest'.
      Assumes docker is already authenticated.
      Example: task push                # Pushes tag from .env or 'latest'
               task push PUSH_TAG=manual # Pushes the 'manual' tag
    vars:
      # PUSH_TAG defaults correctly to global IMAGE_TAG, allows override. Correct.
      PUSH_TAG: '{{.PUSH_TAG | default .IMAGE_TAG }}'
    preconditions:
      # Checks essential vars, docker command. Correct.
      - sh: '[ -n "$REGISTRY_PATH" ]'
        msg: "Error: REGISTRY_PATH is not set in .env file or environment."
      - sh: '[ -n "$IMAGE_NAME" ]'
        msg: "Error: IMAGE_NAME is not set in .env file or environment."
      - sh: "command -v docker"
        msg: "'docker' command not found."
    cmds:
      # Constructs image name, includes auth reminder, runs docker push. Correct.
      - |
        set -e
        IMG_TO_PUSH="${REGISTRY_PATH}/${IMAGE_NAME}:{{.PUSH_TAG}}"
        echo "Pushing $IMG_TO_PUSH ..."
        echo "(Ensure you have authenticated docker with '$REGISTRY_PATH')"
        echo "(e.g., run 'gcloud auth configure-docker $(echo $REGISTRY_PATH | cut -d'/' -f1)' or 'docker login ...')"
        docker push "$IMG_TO_PUSH"
        echo "Push complete: $IMG_TO_PUSH"
    silent: false

  build-push:
    summary: Build and Push the container image with a specific tag.
    desc: |
      # Desc reflects reverted tagging logic. Good.
      Builds the image and then pushes it.
      Default Tag: From .env variable IMAGE_TAG or 'latest'.
      Example: task build-push            # Builds & pushes tag from .env or 'latest'
               task build-push TAG=manual # Builds & pushes 'manual' tag
    vars:
      # TAG defaults correctly to global IMAGE_TAG, allows override. Correct.
      TAG: '{{.TAG | default .IMAGE_TAG }}'
    # No preconditions needed here as called tasks have them. Correct.
    cmds:
      # Calls build and push tasks, passing the TAG correctly. Correct.
      - task: build
        vars: { TAG: "{{.TAG}}" }
      - task: push
        vars: { PUSH_TAG: "{{.TAG}}" }